// @resonance/core — cross-cutting types, errors, and ports shared across packages.
// If something is needed by 2+ packages, it belongs here (ADR-0003). No domain logic.

export { ResonanceError, NotImplementedError, ValidationError } from "./errors";
export { type StoragePort, stubStorage } from "./ports/storage";
export { type MailPort, stubMail } from "./ports/mail";
export { RoleSchema, type Role, type Id } from "./types";
export { InterviewMessageSchema, type InterviewMessage } from "./interview";
export {
  NameOptionSchema,
  type NameOption,
  CreatorProfileDraftSchema,
  type CreatorProfileDraft,
  CommitProfileInputSchema,
  type CommitProfileInput,
} from "./profile-draft";
export { EMBEDDING_DIMS, EmbeddingDimensionError, assertEmbeddingDims } from "./embedding";
// The discovery contract — the swappable ranking seam (ADR-0017). `web` and `ui` depend on
// this and never on `@resonance/db`'s SQL; `db` supplies the adapter behind it.
export {
  RESULT_KINDS,
  ResultKindSchema,
  type ResultKind,
  FOLLOW_STATES,
  FollowStateSchema,
  type FollowState,
  DISCOVERY_DEFAULT_LIMIT,
  DISCOVERY_MAX_LIMIT,
  DiscoveryQuerySchema,
  type DiscoveryQuery,
  CreatorDiscoveryQuerySchema,
  type CreatorDiscoveryQuery,
  CreatorResultSchema,
  type CreatorResult,
  CreatorResultPageSchema,
  type CreatorResultPage,
  type DiscoveryViewer,
  type DiscoveryPort,
} from "./discovery";
// Member interests — the member-side counterpart to the creator interview. `ui` renders the
// picker, `web` validates the submission, `db` stores the selection and embeds it as the
// ranking signal behind `DiscoveryPort` when there is no query text.
export {
  TopicSlugSchema,
  type TopicSlug,
  TopicSchema,
  type Topic,
  MEMBER_INTEREST_TARGET,
  MEMBER_INTEREST_MAX,
  MemberInterestsSchema,
  type MemberInterests,
} from "./interests";
// The Weave OS corpus contracts — the shared vocabulary for Weave's authored behaviour.
// `weave-os` parses and validates it, `ai` composes prompts from it, `db` keys evidence to
// it, and the evolution harness scores against it.
export {
  CorpusIdSchema,
  type CorpusId,
  CorpusValueSchema,
  type CorpusValue,
  GuidanceSchema,
  type Guidance,
  CORPUS_CONFIDENCE_LEVELS,
  CorpusConfidenceSchema,
  type CorpusConfidence,
  CorpusSourceSchema,
  type CorpusSource,
  type CorpusSourceRef,
  readCorpusSource,
  CORPUS_RECORD_STATES,
  CorpusRecordStateSchema,
  type CorpusRecordState,
  CorpusProvenanceSchema,
  type CorpusProvenance,
  CORPUS_FILE_TYPES,
  CorpusFileTypeSchema,
  type CorpusFileType,
  CORPUS_LAYERS,
  CorpusLayerSchema,
  type CorpusLayer,
  CORPUS_FILE_LAYERS,
  CORPUS_FILE_STATUSES,
  CorpusFileStatusSchema,
  type CorpusFileStatus,
  EvolutionPolicySchema,
  type EvolutionPolicy,
  CorpusFileHeaderSchema,
  type CorpusFileHeader,
  type CorpusInheritedBy,
  OsReleaseIdSchema,
  type OsReleaseId,
  InteractionPrincipleSchema,
  type InteractionPrinciple,
  WeaveLimitationSchema,
  type WeaveLimitation,
  BehaviorRuleSchema,
  type BehaviorRule,
  ConversationHeuristicSchema,
  type ConversationHeuristic,
  CorpusFieldSchema,
  type CorpusField,
  FlowCaptureSchema,
  type FlowCapture,
  FlowActionSchema,
  type FlowAction,
  BoundsSchema,
  type Bounds,
  OutputConstraintsSchema,
  type OutputConstraints,
  FlowOutputSchema,
  type FlowOutput,
  FlowStageSchema,
  type FlowStage,
  FlowMapSchema,
  type FlowMap,
  FlowSessionStateSchema,
  type FlowSessionState,
  MinimumInformationSchema,
  type MinimumInformation,
  InteractionPhilosophyFileSchema,
  type InteractionPhilosophyFile,
  InteractionPrinciplesFileSchema,
  type InteractionPrinciplesFile,
  BehaviorRulesFileSchema,
  type BehaviorRulesFile,
  ConversationHeuristicsFileSchema,
  type ConversationHeuristicsFile,
  InterviewFlowFileSchema,
  type InterviewFlowFile,
  CorpusFileSchema,
  type CorpusFile,
} from "./weave-os";
// The sixteen evaluation dimensions: seven principle sub-scores that `principle_alignment`
// decomposes into, plus the nine process/outcome measures.
export {
  SCORE_LABELS,
  type ScoreLabel,
  ScoreSchema,
  type Score,
  EVALUATION_DIMENSIONS,
  EvaluationDimensionSchema,
  type EvaluationDimension,
  COMPOSITE_DIMENSION,
  PROCESS_DIMENSIONS,
  ProcessDimensionSchema,
  type ProcessDimension,
  PRINCIPLE_DIMENSIONS,
  PrincipleDimensionSchema,
  type PrincipleDimension,
  SCORED_DIMENSIONS,
  ScoredDimensionSchema,
  type ScoredDimension,
  SCORED_DIMENSION_COUNT,
} from "./weave-evaluation";
// The observation contract — the evidence-capture seam (ADR-0017). The harness and `ai`
// depend on this and never on `@resonance/db`'s SQL; `db` supplies the adapter behind it.
export {
  OBSERVATION_CATEGORIES,
  ObservationCategorySchema,
  type ObservationCategory,
  EVIDENCE_SOURCES,
  EvidenceSourceSchema,
  type EvidenceSource,
  ObservationSchema,
  type Observation,
  EvaluationScoreSchema,
  type EvaluationScore,
  LimitationVerdictSchema,
  type LimitationVerdict,
  EvaluationSchema,
  type Evaluation,
  type ObservationPort,
} from "./weave-observation";
